/*
 * (C) Copyright IBM Corp. 2020.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.blockchain.v3.model;

import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * ConfigCACrl.
 */
public class ConfigCACrl extends GenericModel {

  protected String expiry;

  /**
   * Builder.
   */
  public static class Builder {
    private String expiry;

    private Builder(ConfigCACrl configCaCrl) {
      this.expiry = configCaCrl.expiry;
    }

    /**
     * Instantiates a new builder.
     */
    public Builder() {
    }

    /**
     * Instantiates a new builder with required properties.
     *
     * @param expiry the expiry
     */
    public Builder(String expiry) {
      this.expiry = expiry;
    }

    /**
     * Builds a ConfigCACrl.
     *
     * @return the new ConfigCACrl instance
     */
    public ConfigCACrl build() {
      return new ConfigCACrl(this);
    }

    /**
     * Set the expiry.
     *
     * @param expiry the expiry
     * @return the ConfigCACrl builder
     */
    public Builder expiry(String expiry) {
      this.expiry = expiry;
      return this;
    }
  }

  protected ConfigCACrl(Builder builder) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(builder.expiry,
      "expiry cannot be null");
    expiry = builder.expiry;
  }

  /**
   * New builder.
   *
   * @return a ConfigCACrl builder
   */
  public Builder newBuilder() {
    return new Builder(this);
  }

  /**
   * Gets the expiry.
   *
   * Expiration of the CRL (Certificate Revocation List) generated by the 'gencrl' requests.
   *
   * @return the expiry
   */
  public String expiry() {
    return expiry;
  }
}

